Add support for zoom
roleoroleo/onvif_simple_server pull request #18
Opened 2024-11-11 23:52 UTC by dvkch

Hi again,

I am currently working on turning an old video conferencing camera into a ONVIF compatible camera. Since the original hardware supports optical zooming I have added the required elements to ONVIF simple server to support those.

I tried to check with the T profile specifications carefully when adding this support, and made sure not to introduce regressions in the existing code for projects that don't use zoom. I hope I have done well on both accounts, but feel free to ask for any changes.

I have also added support for (optional) minimum values for x, y and z in the configuration file, defaulting to 0 if missing. My camera doesn't rotate completely, I ended up putting its coordinate system origin to middle pan, middle tilt and minimum zoom. The only part where I was unsure of their use was for TranslationSpaceFov handling I left it as is for now. If you don't want to support this I can also remove this part from the PR.

Thanks for considering :)

2024-11-15 17:07 UTC, roleoroleo commented
Thank you for your PR.

I ask you if you can make some small fix.
1 - Could you check the cat function? The 3rd parameter is the number of following strings; when you add a new string to replace you have to change this number. For example line 145 of ptz_service.c should be 12.
2 - Line 499, 507, etc.., I don't understand the new parameter "dx" you added to move_* commands. The function continuous_move doesn't use a quantity because it just starts the movement (doesnt' stop it). Please explain me better.

About TranslationSpaceFov I don't know exactly how the zoom should be changed inside this command. Maybe your implementation is ok.

2024-11-15 23:43 UTC, dvkch commented
1/ I’ll make those changes as soon as I’m on my computer. I hadn’t realized that! 

2/ the parameter is actually the speed requested by the client. It is between -1 and 1, the app IPCams in the AppStore uses those to send continuous move requests with different speeds. I saw that you already parsed them properly, simply giving them to the continuous move commands allowed me to map it to my camera ptz requests and have it all work properly. 

3/ I’ll look more into the specs to know if there can be a zoom argument for the Fov, and if so try to support it properly or with reasonable assumptions.

2024-11-26 20:33 UTC, dvkch commented
I have made updates to fix the `cat` issue, as well as rebased on your current master since the media files refacto was conflicting with this patch.

As per Fov, zoom isn't supposed to be included in those requests, the spec v1706 only mentions Pan and tilt translation spaces for this request, as such I have removed it from relative move arguments in this context

2024-11-27 17:49 UTC, roleoroleo commented
Thank you.
I will work on your pr the next weekend.

2024-11-27 19:18 UTC, roleoroleo requested changes
There are a couple of typos. Could you fix them?

2024-11-27 19:18 UTC, roleoroleo commented on ptz_service.c
> +            "%MIN_Z%", min_x,
It should be min_z

2024-11-27 19:18 UTC, roleoroleo commented on ptz_service.c
> +            "%MIN_Y%", min_z,
%MIN_Z%

2024-11-27 19:18 UTC, roleoroleo commented on ptz_service.c
> +            "%MIN_Y%", min_z,
%MIN_Z%

2024-11-28 00:34 UTC, dvkch commented
Sorry about those typos, these should be fixed now

2024-11-29 10:19 UTC, merged